// Sprite — animates AI pet spritesheets generated by the Codex hatch-pet skill.
// Atlas spec: 8 columns x 9 rows of 192x208 cells.
// Animation rows: 0 idle, 1 running-right, 2 running-left, 3 waving,
//                 4 jumping, 5 failed, 6 waiting, 7 running, 8 review.

const CELL_W = 192;
const CELL_H = 208;
const COLS = 8;
const ROWS = 9;
const FPS = 6;

const ROW_BY_STATE = {
  idle: 0,
  wave: 3,
  jump: 4
};

export function initSprite(spriteEl, { src, state = 'idle' } = {}) {
  const reduce = window.matchMedia('(prefers-reduced-motion: reduce)').matches;

  spriteEl.style.width = `${CELL_W}px`;
  spriteEl.style.height = `${CELL_H}px`;
  spriteEl.style.backgroundImage = `url("${src}")`;
  spriteEl.style.backgroundSize = `${CELL_W * COLS}px ${CELL_H * ROWS}px`;

  const ctx = {
    row: ROW_BY_STATE[state] ?? 0,
    frame: 0,
    last: 0,
    raf: 0,
    paused: reduce
  };

  const draw = () => {
    const col = ctx.frame % COLS;
    spriteEl.style.backgroundPosition = `-${col * CELL_W}px -${ctx.row * CELL_H}px`;
  };

  const tick = (now) => {
    if (ctx.paused) return;
    if (!ctx.last) ctx.last = now;
    const dt = now - ctx.last;
    if (dt >= 1000 / FPS) {
      ctx.frame = (ctx.frame + 1) % COLS;
      ctx.last = now;
      draw();
    }
    ctx.raf = requestAnimationFrame(tick);
  };

  const start = () => {
    if (ctx.paused) {
      ctx.paused = false;
      ctx.last = 0;
      ctx.raf = requestAnimationFrame(tick);
    }
  };

  const stop = () => {
    ctx.paused = true;
    cancelAnimationFrame(ctx.raf);
  };

  const setState = (next) => {
    const row = ROW_BY_STATE[next];
    if (row == null) return;
    ctx.row = row;
    ctx.frame = 0;
    ctx.last = 0;
    draw();
  };

  draw();
  if (!reduce) ctx.raf = requestAnimationFrame(tick);

  return { start, stop, setState, isPaused: () => ctx.paused };
}
